<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.ffalcinelli</groupId>
    <artifactId>keycloak-unfold</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>

    <name>Keycloak Unfold</name>
    <description>A custom Keycloak theme designed to emulate the aesthetics of the Django Unfold Theme</description>
    <url>https://github.com/ffalcinelli/keycloak-unfold</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>ffalcinelli</id>
            <name>Fabio Falcinelli</name>
            <email>fabio.falcinelli@gmail.com</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/ffalcinelli/keycloak-unfold.git</connection>
        <developerConnection>scm:git:https://github.com/ffalcinelli/keycloak-unfold.git</developerConnection>
        <url>https://github.com/ffalcinelli/keycloak-unfold</url>
    </scm>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.gpg.plugin.version>3.2.7</maven.gpg.plugin.version>
        <central.publishing.maven.plugin.version>0.10.0</central.publishing.maven.plugin.version>
    </properties>

    <build>
        <finalName>${project.artifactId}-v${project.version}</finalName>
        <resources>
            <!-- Include the theme/ directory from the root of the project -->
            <resource>
                <directory>${project.basedir}</directory>
                <includes>
                    <include>theme/**/*</include>
                </includes>
            </resource>
            <!-- Include the META-INF/ directory from src/main/resources -->
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
                <includes>
                    <include>META-INF/keycloak-themes.json</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <!-- Packaging sources (custom resources) and empty javadocs -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sources-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <classifier>sources</classifier>
                                    <classesDirectory>${project.basedir}</classesDirectory>
                                    <includes>
                                        <include>theme/**/*</include>
                                        <include>src/main/resources/**/*</include>
                                    </includes>
                                </configuration>
                            </execution>
                            <execution>
                                <id>empty-javadoc-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <classifier>javadoc</classifier>
                                    <classesDirectory>${project.basedir}/src/main/resources</classesDirectory>
                                    <includes>
                                        <include>none</include>
                                    </includes>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- GPG Signing of artifacts -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven.gpg.plugin.version}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <gpgArguments>
                                        <arg>--pinentry-mode</arg>
                                        <arg>loopback</arg>
                                    </gpgArguments>
                                    <passphraseEnvName>GPG_PASSPHRASE</passphraseEnvName>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- Deployment to Sonatype Central -->
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${central.publishing.maven.plugin.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>sonatype-central</publishingServerId>
                            <autoPublish>true</autoPublish>
                            <waitUntil>published</waitUntil>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
